server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid: # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒2
      min-evictable-idle-time-millis: 300000

# mybatis别名
mybatis:
  type-aliases-package: com.lsw.userservice.pojo